highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "UTCSSA Soccer"
markdown: rdiscount

author: "Wenjie Luo"
atom-baseurl: "http://soccer.wenjie-luo.com"
# disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: Team
    class: fa fa-users
    href: /team.html
  - title: About
    class: fa fa-bell-o
    href: /about.html

